// This file will be auto-generated by Supabase CLI
// For now, we'll use a placeholder type

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string
          avatar_url: string | null
          created_at: string
        }
        Insert: {
          id: string
          email: string
          full_name: string
          avatar_url?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string
          avatar_url?: string | null
          created_at?: string
        }
      }
      restaurants: {
        Row: {
          id: string
          name: string
          timezone: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          timezone?: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          timezone?: string
          created_at?: string
        }
      }
      restaurant_members: {
        Row: {
          user_id: string
          restaurant_id: string
          role: 'super_admin' | 'admin' | 'worker'
        }
        Insert: {
          user_id: string
          restaurant_id: string
          role?: 'super_admin' | 'admin' | 'worker'
        }
        Update: {
          user_id?: string
          restaurant_id?: string
          role?: 'super_admin' | 'admin' | 'worker'
        }
      }
      availability: {
        Row: {
          id: string
          user_id: string
          date: string
          can_work_morning: boolean
          can_work_afternoon: boolean
        }
        Insert: {
          id?: string
          user_id: string
          date: string
          can_work_morning?: boolean
          can_work_afternoon?: boolean
        }
        Update: {
          id?: string
          user_id?: string
          date?: string
          can_work_morning?: boolean
          can_work_afternoon?: boolean
        }
      }
      shifts: {
        Row: {
          id: string
          restaurant_id: string
          worker_id: string
          start_time: string
          end_time: string
          status: 'draft' | 'published'
          created_at: string
        }
        Insert: {
          id?: string
          restaurant_id: string
          worker_id: string
          start_time: string
          end_time: string
          status?: 'draft' | 'published'
          created_at?: string
        }
        Update: {
          id?: string
          restaurant_id?: string
          worker_id?: string
          start_time?: string
          end_time?: string
          status?: 'draft' | 'published'
          created_at?: string
        }
      }
      weekly_reports: {
        Row: {
          id: string
          restaurant_id: string
          week_start_date: string
          week_end_date: string
          summary_data: Json
          total_hours: number
          created_at: string
        }
        Insert: {
          id?: string
          restaurant_id: string
          week_start_date: string
          week_end_date: string
          summary_data: Json
          total_hours: number
          created_at?: string
        }
        Update: {
          id?: string
          restaurant_id?: string
          week_start_date?: string
          week_end_date?: string
          summary_data?: Json
          total_hours?: number
          created_at?: string
        }
      }
    }
    Views: {}
    Functions: {}
    Enums: {
      user_role: 'super_admin' | 'admin' | 'worker'
      shift_status: 'draft' | 'published'
    }
  }
}
