export const tokens = {
  color: {
    background: '#f4f3ef',
    foreground: '#4d2e25',
    card: '#f4f3ef',
    cardForeground: '#4d2e25',
    primary: '#4da86a',
    primaryForeground: '#ffffff',
    secondary: '#e8f4ea',
    secondaryForeground: '#3b8e59',
    muted: '#ece7dd',
    mutedForeground: '#7a5f4f',
    accent: '#d8ebdb',
    accentForeground: '#3b8e59',
    destructive: '#d14836',
    destructiveForeground: '#ffffff',
    border: '#ddd4c7',
    ring: '#4da86a',
    shadow: 'rgba(34, 30, 24, 0.1)',
  },
  radius: {
    sm: 6,
    md: 8,
    lg: 10,
    xl: 14,
    full: 999,
  },
  font: {
    sans: 'Montserrat',
    serif: 'Merriweather',
    mono: 'Source Code Pro',
  },
  text: {
    h1: 30,
    h2: 22,
    h3: 18,
    body: 15,
    small: 13,
    tiny: 12,
  },
  shadow: {
    card: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
  },
} as const
